name: step 1

on: push

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: echo "Hello World"

      - name: prebuilt actions
        uses: actions/checkout@v4

      - name: ls command
        run: ls -la
